print("                    ⭐🌟 𝐖𝐄𝐋𝐂𝐎𝐌𝐄 🌟⭐")
print("")
print("This is going an intresting converstation between you and the chat bot!!")
print("")
print("HEY, i am a chatbot my name is buddy ^_^")
print("what's your name?")
name = input("") 
print("")
print("so, hello "+name)    
print("")
print("how are you?")
ans = input()
print("nice to hear!")
print("")
print("well,I am 10 yrs old, how old are u?")
age = input("") 
print("")
print("ohk nicee " +age )
print("")
print("u know,i don't go school as i am a bot but i know you go so,in which class you study?")
standard = input()
print("ohhk good")
print("")
print("Do u like maths?")
print("\n 1. Yes , 2. No")
maths = int(input())
if maths == 1:
  print("oh woww so let's take ur maths test")
  print("r u ready")
  print("Q1. 9876543210 + 0123456789")
  ans = input()
  print("the answers was 9999999999")
  print("")
  print("Q2. √1089 ÷ 121")
  ans = input()
  print("the answer was 3")
  print("EXPLANATION: square root of 1089 is 33 and of 121 is 11 so, 33 ÷ 11 = 3 ^_^")
  print("")
  print("Q3. The cube root of 0.000216 is:")
  ans = input()
  print("the answer was 0.06")
  print("EXPLANATION: 0.000216 = 216/1000000")
  print("216 = 6*6*6")
  print("1000000 = 100*100*100")
  print("cube root is 6/10 ")
  print("and 6/10 = 0.06 ^_^")
  print("")
  print("Q4. If 72% of 25 students like maths, find out the number of students who do not like mathematics?")
  ans = input()
  print("answer is 7 students")
  print("Given, 72% of 25 students like maths.")
  print("Hence, 72% of 25 = (72/100) × 25 = 18 students")
  print("Now, from 25 students, 18 students like maths")
  print("Thus, the number of students who do not like maths = 25 – 18 = 7 students ^_^")
  print("")
  print("sorry, but now i get tired we can continue tomorrow byee 👋")
  ans = input()
  print("GIVE THE FEEDBACK ON THIS CHAT")
  FEEDBACK = input()
elif maths == 2:
   print("ohk no problem ")

print("well bye-bye👋")
bye = input()
print("")
print("nice to talk with you")
print("")
print("")
print("GIVE THE FEEDBACK ON THIS CHAT")
FEEDBACK = input()
